# Stable configuration for rustfmt
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Import configuration
reorder_imports = true

# Control where the | is in closure signatures
fn_params_layout = "Tall"

# Control where the ... in a pattern leads/ends a line
match_arm_leading_pipes = "Preserve"
